stages:
   - Building & migration

build:
  stage: Building & migration
  commands:
     - id
     - whoami
     - ls
     - pwd
     - cd /var/jenkins_home
     - ls -ltrha
     - source /var/jenkins_home/.bashrc
     - nvm list
     - node -v
     - npm install
     - ./node_modules/.bin/ng build

pre-build:
  script:
    - ls

post-build:
  script:
    - ls -la

projects:
    - name: Angular
      platform: node:10.16.0-alpine
      commands:
        - apk update && apk add git
        - CHECKOUT
        - npm install
      to-start:
        - ./node_modules/.bin/ng serve --host 0.0.0.0
      service:
        - name: devops-angular
          port: 4200
      mount_path:
        - /src/assets/img1
        - /src/assets/img2
